### ISSUE TITLE
Missing function in module libswiftFoundation.dylib

### ISSUE THREAD

**Issue by eni9889** [maltek/swift-frida#10]
I'm getting the following error when trying to work with swift on iOS 11.3.1:

```
error: Error: missing function '_T0SS10FoundationE8EncodingV4utf8ACfau' in module 'libswiftFoundation.dylib
```

Any feedback would be really helpful

*edit:
This seems to be an issue with swift 4.1.2

**Comment by maltek** [comment]
Yes, Swift 4.1 is unfortunately not yet supported. (It's not just that symbol, something about the type metadata has changed so the current Swift-Frida code just crashes. I haven't had the time to investigate further.)
